name: joystick_menu_button
description: A floating, joystick-style radial menu for touch-driven controls in Flutter. Reveal on long-press and drag to select options.
version: 0.1.0+1
publish_to: https://pub.dev
homepage: https://github.com/mohsenzahab/joystick_menu_button
repository: https://github.com/mohsenzahab/joystick_menu_button

environment:
  sdk: ^3.10.8
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true